export const bibleBooks = [
    {
      section: "Perjanjian Lama",
      books: [
        { name: "Kejadian", chapters: 50 },
        { name: "Keluaran", chapters: 40 },
        { name: "Imamat", chapters: 27 },
        { name: "Bilangan", chapters: 36 },
        { name: "Ulangan", chapters: 34 },
        { name: "Yosua", chapters: 24 },
        { name: "Hakim-hakim", chapters: 21 },
        { name: "Rut", chapters: 4 },
        { name: "1 Samuel", chapters: 31 },
        { name: "2 Samuel", chapters: 24 },
        { name: "1 Raja-raja", chapters: 22 },
        { name: "2 Raja-raja", chapters: 25 },
        { name: "1 Tawarikh", chapters: 29 },
        { name: "2 Tawarikh", chapters: 36 },
        { name: "Ezra", chapters: 10 },
        { name: "Nehemia", chapters: 13 },
        { name: "Ester", chapters: 10 },
        { name: "Ayub", chapters: 42 },
        { name: "Mazmur", chapters: 150 },
        { name: "Amsal", chapters: 31 },
        { name: "Pengkhotbah", chapters: 12 },
        { name: "Kidung Agung", chapters: 8 },
        { name: "Yesaya", chapters: 66 },
        { name: "Yeremia", chapters: 52 },
        { name: "Ratapan", chapters: 5 },
        { name: "Yehezkiel", chapters: 48 },
        { name: "Daniel", chapters: 12 },
        { name: "Hosea", chapters: 14 },
        { name: "Yoel", chapters: 3 },
        { name: "Amos", chapters: 9 },
        { name: "Obaja", chapters: 1 },
        { name: "Yunus", chapters: 4 },
        { name: "Mikha", chapters: 7 },
        { name: "Nahum", chapters: 3 },
        { name: "Habakuk", chapters: 3 },
        { name: "Zefanya", chapters: 3 },
        { name: "Hagai", chapters: 2 },
        { name: "Zakharia", chapters: 14 },
        { name: "Maleakhi", chapters: 4 }
      ]
    },
    {
      section: "Perjanjian Baru",
      books: [
        { name: "Matius", chapters: 28 },
        { name: "Markus", chapters: 16 },
        { name: "Lukas", chapters: 24 },
        { name: "Yohanes", chapters: 21 },
        { name: "Kisah Para Rasul", chapters: 28 },
        { name: "Roma", chapters: 16 },
        { name: "1 Korintus", chapters: 16 },
        { name: "2 Korintus", chapters: 13 },
        { name: "Galatia", chapters: 6 },
        { name: "Efesus", chapters: 6 },
        { name: "Filipi", chapters: 4 },
        { name: "Kolose", chapters: 4 },
        { name: "1 Tesalonika", chapters: 5 },
        { name: "2 Tesalonika", chapters: 3 },
        { name: "1 Timotius", chapters: 6 },
        { name: "2 Timotius", chapters: 4 },
        { name: "Titus", chapters: 3 },
        { name: "Filemon", chapters: 1 },
        { name: "Ibrani", chapters: 13 },
        { name: "Yakobus", chapters: 5 },
        { name: "1 Petrus", chapters: 5 },
        { name: "2 Petrus", chapters: 3 },
        { name: "1 Yohanes", chapters: 5 },
        { name: "2 Yohanes", chapters: 1 },
        { name: "3 Yohanes", chapters: 1 },
        { name: "Yudas", chapters: 1 },
        { name: "Wahyu", chapters: 22 }
      ]
    }
  ];
  