"use client";  

import { useEffect, useState } from 'react';
import Head from 'next/head';
import Header from '../../components/Header';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create app" /> 
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <main className="bg-gray-100 min-h-screen">
                <Header />
            </main> 
        </>
    );
}



// export default function Home() {
//     const [users, setUsers] = useState([]);

//     useEffect(() => {
//         fetchUsers();
//     }, []);

//     async function fetchUsers() {
//         let { data, error } = await supabase.from('reading_progress').select('*');
//         if (error) console.log("Error fetching data:", error);
//         else setUsers(data);
//     }

//     return (
//         <div>
//             <h1>Reading Progress</h1>
//             <ul>
//                 {users.length > 0 ? (
//                     users.map((user) => (
//                         <li key={user.id}>
//                             {user.user_name} is reading {user.book_name} - Chapter {user.chapter_number} ({user.progress_percent}%)
//                         </li>
//                     ))
//                 ) : (
//                     <p>No data found.</p>
//                 )}
//             </ul>
//         </div>
//     );
// }
